import { SVGIcon } from '../models/svg-icon.model';

export const svgIcons: SVGIcon[] = [
  { name: 'authors', fileName: 'author-outline.svg' },
  { name: 'dashboard', fileName: 'dashboard-outline.svg' },
  { name: 'demos', fileName: 'demos.svg' },
  { name: 'filter', fileName: 'filter.svg' },
  { name: 'filter-outlined', fileName: 'filter-outline.svg' },
  { name: 'tips', fileName: 'tips-outline.svg' },
  { name: 'settings', fileName: 'settings-outline.svg' },
  { name: 'links', fileName: 'link.svg' },
  { name: 'tags', fileName: 'tags.svg' },
  { name: 'double_arrow', fileName: 'double_arrow.svg' },
  { name: 'dark_mode', fileName: 'dark_mode.svg' },
  { name: 'light_mode', fileName: 'light_mode.svg' },
  { name: 'logout', fileName: 'logout.svg' },
  { name: 'ic_google_logo', fileName: 'ic_google_logo.svg' },
  { name: 'group', fileName: 'group-outline.svg' },
  { name: 'receipt', fileName: 'receipt-outline.svg' },
  { name: 'currency-rupee', fileName: 'currency-rupee.svg' },
  { name: 'add-business', fileName: 'add-business-outline.svg' },
  { name: 'shopping-cart', fileName: 'shopping-cart-outline.svg' },
  { name: 'payments', fileName: 'payments-outline.svg' },
  { name: 'account-balance', fileName: 'account-balance-outline.svg' },
  { name: 'category', fileName: 'category-outline.svg' },
];
